### ISSUE TITLE
How do you use  loading widget in vm ?

### ISSUE THREAD

**Issue by onlyYU** [bladeofgod/Bedrock#12]
suggest:
make loading widget global, such as EasyLoading

**Comment by bladeofgod** [comment]
EasyLoading's mechanism is used root key or Overlay, i think.  and in my experience,  it will cause some bug that difficult to track .
so.in this framework ,the Loading widget is work like a page , and it's draw on flutter's design. 

and for your question, you can code like this:

class YourVM {

 Future apiRequest() {
   final Completer completer = Completer();
   api.startRequest().then(() {
           .....
          completer.complete;
     });
  return completer.furture;
}

}

class YourPage {

   showLoading();
  
  YourVM.apiRequest().then(() = > hideLoading());

}
