### ISSUE TITLE
clone项目之后iOS无法运行

### ISSUE THREAD

**Issue by JarynChen** [bladeofgod/Bedrock#14]
![image](https://user-images.githubusercontent.com/41881490/132818461-c0cf2b93-bbcb-40b7-8b8c-666b64dce26c.png)

**Comment by zys5566** [comment]
null safety 把插件版本更新到有处理null safety版本就好了，下面的问题我也遇到了

**Comment by bladeofgod** [comment]
你好，谢谢反馈，明天我核查一下看看哪些插件未更新。

**Comment by bladeofgod** [comment]
你好， 拉去代码可以正常运行，你可以将框架插件升级到最新版本试试。
