### ISSUE TITLE
运行框架，引入的插件方法报错，另外挺多插件空安全警告，建议更新版本

### ISSUE THREAD

**Issue by zys5566** [bladeofgod/Bedrock#15]
/C:/Users/js03/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/dokit-0.8.0-nullsafety.0/lib/engine/dokit_binding.dart:128:12: Error: The method 'setMockMessageHandler' isn't defined for the class 'BinaryMessenger'.
 - 'BinaryMessenger' is from 'package:flutter/src/services/binary_messenger.dart' ('../../flutter/packages/flutter/lib/src/services/binary_messenger.dart').
Try correcting the name to the name of an existing method, or defining a method named 'setMockMessageHandler'.
    origin.setMockMessageHandler(channel, handler);
           ^^^^^^^^^^^^^^^^^^^^^
/C:/Users/js03/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/dokit-0.8.0-nullsafety.0/lib/engine/dokit_binding.dart:138:52: Error: The argument type 'Future<ByteData?>? Function(ByteData?)?' can't be assigned to the parameter type 'Future<ByteData?>? Function(ByteData?)' because 'Future<ByteData?>? Function(ByteData?)?' is nullable and 'Future<ByteData?>? Function(ByteData?)' isn't.
 - 'Future' is from 'dart:async'.
 - 'ByteData' is from 'dart:typed_data'.
    return origin.checkMockMessageHandler(channel, handler);
                                                   ^
/C:/Users/js03/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/dokit-0.8.0-nullsafety.0/lib/engine/dokit_http.dart:77:27: Error: A value of type 'Future<bool> Function(Uri, String, String)?' can't be assigned to a variable of type 'Future<bool> Function(Uri, String, String?)?' because 'String?' is nullable and 'String' isn't.
 - 'Future' is from 'dart:async'.
 - 'Uri' is from 'dart:core'.
    origin.authenticate = f;
                          ^
/C:/Users/js03/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/dokit-0.8.0-nullsafety.0/lib/engine/dokit_http.dart:84:32: Error: A value of type 'Future<bool> Function(String, int, String, String)?' can't be assigned to a variable of type 'Future<bool> Function(String, int, String, String?)?' because 'String?' is nullable and 'String' isn't.
 - 'Future' is from 'dart:async'.
    origin.authenticateProxy = f;
                               ^

**Comment by bladeofgod** [comment]
你好，谢谢反馈，明天我核查一下看看哪些插件未更新。

**Comment by bladeofgod** [comment]
你好， 拉去代码可以正常运行，你可以将框架依赖的插件升级到最新版本试试。
