### ISSUE TITLE
拉取最新代码无法运行？

### ISSUE THREAD

**Issue by andya1985** [bladeofgod/Bedrock#17]
请问最新版的代码，flutter版本、androidstudio版本、dart版本分别是多少啊。我这里运行不起来
我分别用了flutter2.8.1最新的，flutter2.0.0,flutter2.5.3.androidsutdio版本是最新的，都运行不起来。

![1640767666(1)](https://user-images.githubusercontent.com/10007321/147643818-58d59673-1795-49fa-8884-5d8b48d9e49b.jpg)
![image](https://user-images.githubusercontent.com/10007321/147644357-e205c862-87a8-4d60-9015-db87185b7622.png)

**Comment by andya1985** [comment]
如果方便的话，在readme里标注一下相应的版本号

**Comment by bladeofgod** [comment]
你好，我是flutter 2.5， v2.1.5 是可以正常运行的。
根据你的日志来看，可以尝试引入decimal.dart这个路径，而不是money_util.dart这个库路径。
另外，我看了一下commonUtil 这个库，发现他的文档建议纯dart项目才依赖此库，否则使用flustars。 
我已经将common util这个库注释，并更新版本到v2.1.6。
