### ISSUE TITLE
ExceptionBinding是如何使ViewModel对内部api进行异常捕获和监听调用的？

### ISSUE THREAD

**Issue by chaooWoo** [bladeofgod/Bedrock#18]
看到这个功能的更新：ExceptionBinding，使viewModel可以对内部的所有api接口的异常捕获

目前我的view model实现了ExceptionBinding的notifyException方法以及监听者注册，但是看了框架代码之后，没发现在什么地方来调用注册的监听。麻烦能不能解释一下？谢谢了大佬!!

注：
1.只在exception_pitcher.dart中看到view model   InitData()的异常状态捕获
2.未看到其他地方对非initData()的api异常监听回调使用

**Comment by chaooWoo** [comment]
我当前的理解是notifyException()方法可以处理判断抛出何种异常，以及api请求的数据responseData，但是不知框架何处来处理这些注册监听者回调。 有看到demo中的示例，但未能理解，看到问题麻烦描述一下，谢谢了

**Comment by chaooWoo** [comment]
@bladeofgod

**Comment by bladeofgod** [comment]
你好，刚才我查看了这里的代码，发现对应没有实现，因为时间太久远，所以具体啥原因也忘了
![01D2185F](https://user-images.githubusercontent.com/34591987/154936923-c203effa-bc46-41d9-b1aa-c2877c2478d3.png)
。

**Comment by bladeofgod** [comment]
目前已经补全对应功能，并且适配了flutter 2.10 ， 最新版本号： 2.2.0

**Comment by Chaos-woo** [comment]
好的，谢谢大佬啦。后续我根据更新内容补全一下我的代码。 @bladeofgod
