### ISSUE TITLE
dialog 的问题

### ISSUE THREAD

**Issue by lixin1203** [bladeofgod/Bedrock#3]
在BaseState里面的show对话框，我看到是直接push一个页面，什么都好，就是没处理好返回键的时候，只要show之后按下返回键，就再也show不出来了

**Comment by bladeofgod** [comment]
是个 bug 谢谢反馈，这就修复。

**Comment by bladeofgod** [comment]
> 在BaseState里面的show对话框，我看到是直接push一个页面，什么都好，就是没处理好返回键的时候，只要show之后按下返回键，就再也show不出来了

问题已修复，谢谢你的反馈
