### ISSUE TITLE
用系统的BottomNavigationBar构建报错

### ISSUE THREAD

**Issue by GreatLiyi** [bladeofgod/Bedrock#5]
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bedrock/base_framework/widget_state/base_state.dart';
import 'package:flutter_bedrock/base_framework/widget_state/page_state.dart';
import 'package:flutter_bedrock/page/demo_page/main/first_page.dart';
import 'package:flutter_bedrock/page/demo_page/main/second_page.dart';
import 'package:flutter_bedrock/page/demo_page/main/third_page.dart';
import 'package:oktoast/oktoast.dart';

import 'first_page.dart';
import 'second_page.dart';

typedef TransportScrollController = Function(ScrollController controller);

List<BottomNavigationBarItem> itemList() {
  return [
    BottomNavigationBarItem(
      title: Text("首页"),
      // activeIcon: Image.asset(TKImages.tabbar_home_select, fit: BoxFit.contain),
      // icon: Image.asset(TKImages.tabbar_home_unselect, fit: BoxFit.contain)
      icon: Icon(Icons.home),
    ),
    BottomNavigationBarItem(
      title: Text("动态"),
      // activeIcon: Image.asset(TKImages.tabbar_find_select, fit: BoxFit.contain),
      // icon: Image.asset(TKImages.tabbar_find_unselect, fit: BoxFit.contain)
      icon: Icon(Icons.insert_invitation),
    ),
    BottomNavigationBarItem(
      title: Container(),
      // icon: Image.asset(TKImages.tabbar_add, fit: BoxFit.contain),
      icon: Icon(
        Icons.add_circle,
        size: 44,
      ),
    ),
    BottomNavigationBarItem(
      title: Text("消息"),
      // activeIcon: Image.asset(TKImages.tabbar_school_select, fit: BoxFit.contain),
      // icon: Image.asset(TKImages.tabbar_school_unselect, fit: BoxFit.contain)
      icon: Icon(Icons.chrome_reader_mode),
    ),
    BottomNavigationBarItem(
      title: Text("我的"),
      // activeIcon: Image.asset(TKImages.tabbar_mine_select, fit: BoxFit.contain),
      // icon: Image.asset(TKImages.tabbar_mine_unselect, fit: BoxFit.contain)
      icon: Icon(Icons.person),
    ),
  ];
}

class MainPageState1 extends PageState {
  final PageController pageController = PageController();
  int selectIndex = 0;

  ScrollController firstController;

  DateTime lastPress;

  jumpByIndex(int index) {
    pageController.jumpToPage(index);
  }

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
  }

  int _currentIndex = 0;

  final List<Widget> pageList = [
    // FindPage(),
    FirstPageState(null).generateWidget(),
    SecondPageState().generateWidget(),
    SecondPageState().generateWidget(),
    SecondPageState().generateWidget(),
  ];

  @override
  Widget build(BuildContext context) {
    return switchStatusBar2Dark(
        isSetDark: true,
        child: Container(
          color: Colors.white,
          width: getWidthPx(750),
          height: getHeightPx(1334),
          child: Scaffold(
            body: IndexedStack(
              index: _currentIndex,
              children: pageList,
            ),
            bottomNavigationBar: BottomNavigationBar(
              backgroundColor: Colors.red,
              items: itemList(),
              type: BottomNavigationBarType.fixed,
              currentIndex: _currentIndex,
              selectedFontSize: 10,
              unselectedFontSize: 10,
              selectedIconTheme: IconThemeData(
                size: 24,
              ),
              unselectedIconTheme: IconThemeData(size: 24),
              onTap: (index) {
                if (index == 2) {}
                setState(() {
                  _currentIndex = index;
                });
              },
            ),
          ),
        ));
  }

  Widget normalIcon(IconData iconData) {
    return Icon(
      iconData,
      color: Colors.grey,
    );
  }

  Widget activeIcon(IconData iconData) {
    return Icon(
      iconData,
      color: Colors.blue,
    );
  }

  Widget buildBottomItem({
    int index,
    Icon icon,
    Icon iconActive,
  }) {
    return GestureDetector(
      onTap: () {
        if (selectIndex != index) {
          pageController.jumpToPage(index);
        } else if (selectIndex == 0) {
          firstController?.animateTo(0,
              duration: Duration(microseconds: 500), curve: Curves.easeIn);
        }
      },
      child: Container(
        width: getWidthPx(80),
        height: getWidthPx(80),
        child: selectIndex == index ? iconActive : icon,
      ),
    );
  }
}

报错信息如下

════════ Exception caught by rendering library ═════════════════════════════════
Each child must be laid out exactly once.
The relevant error-causing widget was
Scaffold

**Comment by bladeofgod** [comment]
建议更新 flutter，同时清空缓存。
另外建议看一下我项目demo中的 ‘综合demo’，此demo 代码是对项目功能的一个综合性介绍且代码简单。

然后再看一下更复杂一些的项目：
https://juejin.cn/post/6881093329317019662/  
https://github.com/bladeofgod/cloud_music

**Comment by GreatLiyi** [comment]
> 建议更新 flutter，同时清空缓存。
> 另外建议看一下我项目demo中的 ‘综合demo’，此demo 代码是对项目功能的一个综合性介绍且代码简单。
> 
> 然后再看一下更复杂一些的项目：
> https://juejin.cn/post/6881093329317019662/
> https://github.com/bladeofgod/cloud_music

你试了那段代码没报错吗,我清了缓存和flutter是最新版的
