### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by jasonlee3652** [bladeofgod/Bedrock#7]
项目无法启动
`flutter Invalid `Podfile` file: no implicit conversion of nil into String`
请问项目还需要怎么配置吗?网上的方案都试过了，始终无法运行。

**Comment by bladeofgod** [comment]
应该是环境配置有问题。 你可以参考这个：

https://github.com/cocoapods/cocoapods/issues/6381#issuecomment-285403061

**Comment by bladeofgod** [comment]
还有这个：
https://github.com/cocoapods/cocoapods/issues/6381#issuecomment-331292815

**Comment by bladeofgod** [comment]
没有问题的话，过几天我就把这个issue 关喽~
