### ISSUE TITLE
android上启动： The number of method references in a .dex file cannot exceed 64K. 

### ISSUE THREAD

**Issue by 164250072** [bladeofgod/Bedrock#8]

**Comment by bladeofgod** [comment]
百度， 安卓解决方法超出64k 问题。

**Comment by bladeofgod** [comment]
话说这个框架原生端基本没有东西，你是如何遇到这个异常的？ 是老项目的接入吗？

**Comment by 164250072** [comment]
> 话说这个框架原生端基本没有东西，你是如何遇到这个异常的？ 是老项目的接入吗？

拉下来后，直接使用vscode真机运行

**Comment by bladeofgod** [comment]
原生使用multidex插件，然后开启即可。



---原始邮件---
发件人: "164250072"<notifications@github.com&gt;
发送时间: 2021年1月14日(周四) 中午1:07
收件人: "bladeofgod/Bedrock"<Bedrock@noreply.github.com&gt;;
抄送: "bladeofgod"<450103187@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [bladeofgod/Bedrock] android上启动： The number of method references in a .dex file cannot exceed 64K.  (#8)




  
话说这个框架原生端基本没有东西，你是如何遇到这个异常的？ 是老项目的接入吗？
  
拉下来后，直接使用vscode真机运行

**Comment by 164250072** [comment]
可能是我这边的问题吧，直接运行这个框架没有问题。我的是项目才开始，另一个兄弟在苹果上做了两个页面跑通了后，我拉到android上调，就报这个错。  解决方法我问度娘了， thank you
> 话说这个框架原生端基本没有东西，你是如何遇到这个异常的？ 是老项目的接入吗？

**Comment by bladeofgod** [comment]
> 可能是我这边的问题吧，直接运行这个框架没有问题。我的是项目才开始，另一个兄弟在苹果上做了两个页面跑通了后，我拉到android上调，就报这个错。 解决方法我问度娘了， thank you
> 
> > 话说这个框架原生端基本没有东西，你是如何遇到这个异常的？ 是老项目的接入吗？

没事，如果觉得框架哪里设计的有不妥的，或者有些通用型功能欠缺，欢迎提出来。
