### ISSUE TITLE
flutter sdk 2.0的可以改下空安全迁移吗

### ISSUE THREAD

**Issue by szxv587** [bladeofgod/Bedrock#9]

**Comment by SheepYang1993** [comment]
+1

**Comment by bladeofgod** [comment]
> @bladeofgod 提交了升级到空安全的代码 #11

非常感谢你的帮助。

**Comment by szxv587** [comment]
Because extended_image_library 0.2.3 depends on path_provider ^1.1.2 and no versions of extended_image_library match >0.2.3 <0.3.0, extended_image_library ^0.2.3 requires path_provider ^1.1.2.
And because extended_image 0.8.0 depends on extended_image_library ^0.2.3 and no versions of extended_image match >0.8.0 <0.9.0, extended_image ^0.8.0 requires path_provider ^1.1.2.
So, because flutter_bedrock depends on both path_provider ^2.0.1 and extended_image ^0.8.0, version solving failed.
pub get failed (1; So, because flutter_bedrock depends on both path_provider ^2.0.1 and extended_image ^0.8.0, version solving failed.)

我升级了插件版本，这个怎么解决呢？

**Comment by szxv587** [comment]
@bladeofgod

**Comment by szxv587** [comment]
@bladeofgod 如果在原项目上升级flutter sdk 为2.0，除了升级插件外还需要改哪部分呢？

**Comment by bladeofgod** [comment]
> @bladeofgod 如果在原项目上升级flutter sdk 为2.0，除了升级插件外还需要改哪部分呢？

flutter和对应插件都迁移到2.0 就可以了，前提是插件本身也升级到了2.0.
具体你可以参考：https://juejin.cn/post/6938342360833064974
这篇文章。

PS：如果是比较有规模的老项目，不建议贸然升级，可能会有一些麻烦，或者在时间充裕的时候做这件事情。

**Comment by szxv587** [comment]
@bladeofgod  感谢！！可是我又遇到问题了

Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:pull_to_refresh
 - package:flutter_swiper
 - package:scrollable_positioned_list
 - package:flutter_page_indicator
 - package:transformer_page_view

**Comment by onlyYU** [comment]
environment:
  sdk: ">=2.12.0 <3.0.0"

path_provider: any

其他的全部升级到最新，我是这样解决的

**Comment by bladeofgod** [comment]
> @bladeofgod 感谢！！可是我又遇到问题了
> 
> Error: Cannot run with sound null safety, because the following dependencies
> don't support null safety:
> 
> * package:pull_to_refresh
> * package:flutter_swiper
> * package:scrollable_positioned_list
> * package:flutter_page_indicator
> * package:transformer_page_view

你可以查看这个插件是否支持了 空安全版本，如果没有的话，就没办法了，哈哈。
另外，你可以参考楼上的方法  @onlyYU

**Comment by onlyYU** [comment]
> > @bladeofgod 感谢！！可是我又遇到问题了
> > Error: Cannot run with sound null safety, because the following dependencies
> > don't support null safety:
> > 
> > * package:pull_to_refresh
> > * package:flutter_swiper
> > * package:scrollable_positioned_list
> > * package:flutter_page_indicator
> > * package:transformer_page_view
> 
> 你可以查看这个插件是否支持了 空安全版本，如果没有的话，就没办法了，哈哈。
> 另外，你可以参考楼上的方法 @onlyYU



> @bladeofgod 感谢！！可是我又遇到问题了
> 
> Error: Cannot run with sound null safety, because the following dependencies
> don't support null safety:
> 
> * package:pull_to_refresh
> * package:flutter_swiper
> * package:scrollable_positioned_list
> * package:flutter_page_indicator
> * package:transformer_page_view

pub.dev好多库是不支持 null safety 的，你可以在他们的Issues中找答案，或者fork自己修改
